version: '2'
services:
  pretalx:
    image: maxrink/pretalx-devel:latest
    container_name: pretalx
    networks: 
      - pretalx
      - web
    depends_on: db
    volumes: 
      - ./conf/pretalx.cfg:/etc/pretalx.cfg:ro
      - pretalx-data:/data


  db:
    image: mysql:5
    container_name: pretalx-db
    networks: 
      - pretalx
    volumes:
      - pretalx-db:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: pretalx-redis
    networks: 
      - pretalx
    volumes: 
      - pretalx-redis:/data


volumes:
  pretalx-db:
  pretalx-data:
  pretalx-redis:

  
networks:
  pretalx:
  web: