version: '2'
services:
  pretalx:
    image: maxrink/pretalx-devel:latest
    container_name: pretalx
    restart: unless-stopped
    networks: 
      - pretalx
      - web
    depends_on: 
      - redis
      - db
    ports:
      - "3080:80"
    volumes: 
      - ./conf/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - pretalx-data:/data


  db:
    image: mysql:5
    container_name: pretalx-db
    restart: unless-stopped
    networks: 
      - pretalx
    volumes:
      - pretalx-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pretalx
      MYSQL_USER: pretalx
      MYSQL_PASSWORD: veryunsecureplschange
      MYSQL_RANDOM_ROOT_PASSWORD: "1"

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: unless-stopped
    networks: 
      - pretalx
    volumes: 
      - pretalx-redis:/data


volumes:
  pretalx-db:
  pretalx-data:
  pretalx-redis:

  
networks:
  pretalx:
  web: